%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1         
num_of_cam: 1  

imu_topic: "/zed/imu/data_raw"
image0_topic: "/zed/left/image_rect_color"
image1_topic: "/zed/right/image_rect_color"
output_path: "~/output/"

cam0_calib: "cam_pinhole_l.yaml"
cam1_calib: "cam_pinhole_r.yaml"
image_width: 672
image_height: 376
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [0.0014846158067664955, -0.9999566394077031, -0.009193215996598725, 0.0026856085760216626,
          0.026265352079174964, 0.009229046866280219, -0.9996124028712818, 0.0009023689144005919,
          0.9996539037067099, 0.0012425773190519185, 0.02627791478681095, 0.0006287860401229842,
          0, 0, 0, 1]
body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [-0.0016843852880614036, -0.9999562677393219, -0.009199209479474446, -0.06711970546466307,
           0.025674324312040753, 0.009152946405229194, -0.9996284572996227, 0.0022119334059672777,
           0.9996689411586828, -0.0019199429545934121, 0.02565778442752982, 0.0006892909975584863,
           0, 0, 0, 1]

#Multiple thread support
multiple_thread: 8

#feature traker paprameters
max_cnt: 110            # max feature number in feature tracking
min_dist: 18            # min distance between two features 
freq: 0                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1        # ransac threshold (pixel)
show_track: 0          # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.045  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.1          # accelerometer measurement noise standard deviation. 
gyr_n: 0.01         # gyroscope measurement noise standard deviation.     
acc_w: 0.001        # accelerometer bias random work noise standard deviation.  
gyr_w: 0.0001       # gyroscope bias random work noise standard deviation.     
g_norm: 9.81007     # gravity magnitude

#unsynchronization parameters
estimate_td: 1                      # online estimate time offset between camera and imu
td: -0.04                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "~/output/pose_graph/" # save and load path
save_image: 0                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
